apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-demo
  namespace: deployment.yml-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: deployment.yml-demo
  project: default
  source:
    repoURL: https://github.com/mehdikhelif/argocd.git
    path: deployment.yml/resources
    targetRevision: main